import { ImageSourcePropType } from "react-native";

export interface DATA_TYPE {
    name: string;
    timezone: string;
    day_of_week: string;
    available_at: string;
    available_until: string;
    image: ImageSourcePropType
    skills: string[],
    timeSlots?: TIME_SLOT[]
}

export interface TIME_SLOT {
    id: string;
    slots: string[]
    booked: boolean
}

export const DATA : DATA_TYPE[]= [
    {
      "name": "Christy Schumm",
      "timezone": "Australia/Sydney",
      "day_of_week": "Monday",
      "available_at": "9:00AM",
      "available_until": "17:30PM",
      "image": require('./assets/images/christy.jpg'),
      skills: ['Yoga', 'Meditation', 'Pilates'],
    },
    {
      "name": "Christy Schumm",
      "timezone": "Australia/Sydney",
      "day_of_week": "Tuesday",
      "available_at": "8:00AM",
      "available_until": "16:00PM",
      "image": require('./assets/images/christy.jpg'),
      skills: ['Yoga', 'Meditation', 'Pilates'],
    },
    {
      "name": "Christy Schumm",
      "timezone": "Australia/Sydney",
      "day_of_week": "Thursday",
      "available_at": "9:00AM",
      "available_until": "16:00PM",
      "image": require('./assets/images/christy.jpg'),
      skills: ['Yoga', 'Meditation', 'Pilates'],
    },
    {
      "name": "Christy Schumm",
      "timezone": "Australia/Sydney",
      "day_of_week": "Friday",
      "available_at": "7:00AM",
      "available_until": "14:00PM",
      "image": require('./assets/images/christy.jpg'),
      skills: ['Yoga', 'Meditation', 'Pilates'],
    },
    {
      "name": "Natalia Stanton Jr.",
      "timezone": "Australia/Perth",
      "day_of_week": "Tuesday",
      "available_at": "8:00AM",
      "available_until": "10:00AM",
      "image": require('./assets/images/natalia.jpg'),
      skills: ['Gymnastics', 'Weightlifting', 'Swimming'],
    },
    {
      "name": "Natalia Stanton Jr.",
      "timezone": "Australia/Perth",
      "day_of_week": "Wednesday",
      "available_at": "11:00AM",
      "available_until": "18:00PM",
      "image": require('./assets/images/natalia.jpg'),
      skills: ['Gymnastics', 'Weightlifting', 'Swimming'],
    },
    {
      "name": "Natalia Stanton Jr.",
      "timezone": "Australia/Perth",
      "day_of_week": "Saturday",
      "available_at": "9:00AM",
      "available_until": "15:00PM",
      "image": require('./assets/images/natalia.jpg'),
      skills: ['Gymnastics', 'Weightlifting', 'Swimming'],
    },
    {
      "name": "Natalia Stanton Jr.",
      "timezone": "Australia/Perth",
      "day_of_week": "Sunday",
      "available_at": "8:00AM",
      "available_until": "15:00PM",
      "image": require('./assets/images/natalia.jpg'),
      skills: ['Gymnastics', 'Weightlifting', 'Swimming'],
    },
    {
      "name": "Nola Murazik V",
      "timezone": "Australia/Darwin",
      "day_of_week": "Monday",
      "available_at": "8:00AM",
      "available_until": "10:00AM",
      "image": require('./assets/images/natalia.jpg'),
      skills: ['Bodybuilding', 'Weightlifting', 'Swimming'],
    },
    {
      "name": "Nola Murazik V",
      "timezone": "Australia/Darwin",
      "day_of_week": "Tuesday",
      "available_at": "11:00AM",
      "available_until": "13:00PM",
      "image": require('./assets/images/nola.jpg'),
      skills: ['Bodybuilding', 'Weightlifting', 'Swimming'],
    },
    {
      "name": "Nola Murazik V",
      "timezone": "Australia/Darwin",
      "day_of_week": "Wednesday",
      "available_at": "8:00AM",
      "available_until": "10:00AM",
      "image": require('./assets/images/nola.jpg'),
      skills: ['Bodybuilding', 'Weightlifting', 'Swimming'],
    },
    {
      "name": "Nola Murazik V",
      "timezone": "Australia/Darwin",
      "day_of_week": "Saturday",
      "available_at": "8:00AM",
      "available_until": "11:00AM",
      "image": require('./assets/images/nola.jpg'),
      skills: ['Bodybuilding', 'Weightlifting', 'Swimming'],
    },
    {
      "name": "Nola Murazik V",
      "timezone": "Australia/Darwin",
      "day_of_week": "Sunday",
      "available_at": "7:00AM",
      "available_until": "9:00AM",
      "image": require('./assets/images/nola.jpg'),
      skills: ['Bodybuilding', 'Weightlifting', 'Swimming'],
    },
    {
      "name": "Elyssa O'Kon",
      "timezone": "Australia/Perth",
      "day_of_week": "Monday",
      "available_at": "9:00AM",
      "available_until": "15:00PM",
      "image": require('./assets/images/elysa.jpg'),
      skills: ['Painting', 'Drawing', 'Photography'],
    },
    {
      "name": "Elyssa O'Kon",
      "timezone": "Australia/Perth",
      "day_of_week": "Tuesday",
      "available_at": "6:00AM",
      "available_until": "13:00PM",
      "image": require('./assets/images/elysa.jpg'),
      skills: ['Painting', 'Drawing', 'Photography'],
    },
    {
      "name": "Elyssa O'Kon",
      "timezone": "Australia/Perth",
      "day_of_week": "Wednesday",
      "available_at": "6:00AM",
      "available_until": "11:00AM",
      "image": require('./assets/images/elysa.jpg'),
      skills: ['Painting', 'Drawing', 'Photography'],
    },
    {
      "name": "Elyssa O'Kon",
      "timezone": "Australia/Perth",
      "day_of_week": "Friday",
      "available_at": "8:00AM",
      "available_until": "12:00PM",
      "image": require('./assets/images/elysa.jpg'),
      skills: ['Painting', 'Drawing', 'Photography'],
    },
    {
      "name": "Elyssa O'Kon",
      "timezone": "Australia/Perth",
      "day_of_week": "Saturday",
      "available_at": "9:00AM",
      "available_until": "16:00PM",
      "image": require('./assets/images/elysa.jpg'),
      skills: ['Painting', 'Drawing', 'Photography'],
    },
    {
      "name": "Elyssa O'Kon",
      "timezone": "Australia/Perth",
      "day_of_week": "Sunday",
      "available_at": "8:00AM",
      "available_until": "10:00AM",
      "image": require('./assets/images/elysa.jpg'),
      skills: ['Painting', 'Drawing', 'Photography'],
    },
    {
      "name": "Dr. Geovany Keebler",
      "timezone": "Australia/Perth",
      "day_of_week": "Thursday",
      "available_at": "7:00AM",
      "available_until": "14:00PM",
      "image": require('./assets/images/geovany.jpg'),
      skills: ['Gardening', 'Weightlifting', 'Swimming'],
    },
    {
      "name": "Dr. Geovany Keebler",
      "timezone": "Australia/Perth",
      "day_of_week": "Thursday",
      "available_at": "3:00PM",
      "available_until": "17:00PM",
      "image": require('./assets/images/geovany.jpg'),
      skills: ['Gardening', 'Weightlifting', 'Swimming'],
    },
    {
      "name": "Ramy Malik",
      "timezone": "Australia/Perth",
      "day_of_week": "Monday",
      "available_at": "9:00AM",
      "available_until": "15:00PM",
      "image": require('./assets/images/ramy.jpg'),
      skills: ['Computer', 'Programming', 'Web Development'],
    },
    {
      "name": "Ramy Malik",
      "timezone": "Australia/Perth",
      "day_of_week": "Tuesday",
      "available_at": "6:00AM",
      "available_until": "13:00PM",
      "image": require('./assets/images/ramy.jpg'),
      skills: ['Computer', 'Programming', 'Web Development'],
    },
    {
      "name": "Ramy Malik",
      "timezone": "Australia/Perth",
      "day_of_week": "Wednesday",
      "available_at": "6:00AM",
      "available_until": "11:00AM",
      "image": require('./assets/images/ramy.jpg'),
      skills: ['Computer', 'Programming', 'Web Development'],
    },
    {
      "name": "Ramy Malik",
      "timezone": "Australia/Perth",
      "day_of_week": "Friday",
      "available_at": "8:00AM",
      "available_until": "12:00PM",
      "image": require('./assets/images/ramy.jpg'),
      skills: ['Computer', 'Programming', 'Web Development'],
    }
  ]